### ISSUE TITLE
cannot found DAVIS_2017_val.txt and DAVIS_2017_val.txt 

### ISSUE THREAD

**Issue by cxy86121** [griffbr/BubbleNets#10]
Dear author:
I want to know where to find "  the DAVIS_2017_val.txt and DAVIS_2017_val.txt  " file?

When I run the" train_annotate_net_on_DAVIS17.py" I can't find the file.

Pls.thanks a lot!

**Comment by griffbr** [comment]
This is a question related to a file that I emailed you separately, so this question isn't useful for the repository. Please check your email for reply.
