### ISSUE TITLE
what kind of vos model is suitable for the task given the annotation which is not the first?

### ISSUE THREAD

**Issue by cjfcsjt** [griffbr/BubbleNets#7]
Hi! After reading your excellent work, I have a question. The bubblenet is able to find the 'best frame ' for annotation, but after finding this frame (e.g. the middle frame with annotation), what kind of vos model is suitable for the task given the annotation which is not the first? Maybe some vos methods request that the annotation should be the first.

**Comment by griffbr** [comment]
Hello cjfcsjt,

Great question! The short answer is **ANY** semi-supervised method.

Here's why. Even if a vos model assumes first frame annotation and requires sequential operation, the video can be "split" forward _and backward_ from any annotation frame later in the video (e.g., middle frame annotation). In fact, we did this with OnAVOS, which is a sequential vos method (Table 6 in our paper). Basically, we propagate the vos model forward from the annotation frame just as if it had been first frame annotation, then we treat the frames prior to the annotation frame as a "backwards" video and propagate the vos model back to the first frame. The vos model doesn't know the difference.

I hope this explanation helps. Do let me know if there is anything I can clarify or if you have any other questions.

Best,
Brent
